databaseChangeLog:
  - include:
      file: changesets/001_create_assets_table.yaml
  - include:
      file: changesets/002_create_app_config_table.yaml
  - include:
      file: changesets/003_create_notify_function.yaml
  - include:
      file: changesets/004_create_notify_trigger.yaml
  - include:
      file: changesets/005_create_add_asset_procedure.yaml
  - include:
      file: changesets/006_create_audit_log_table.yaml
  - include:
      file: changesets/007_add_seed_assets.yaml
  - include:
      file: changesets/008_add_seed_app_config.yaml

