apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-update
  namespace: assetops
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase
          image: assetops-liquibase:local
          imagePullPolicy: Never
          command:
            - /liquibase/docker-entrypoint.sh
          args:
            - --defaultsFile=/liquibase/infra/liquibase/liquibase.yaml
            - update
