CALL add_asset ('Compressor 01', 'Plant A', 'Idle');
CALL add_asset ('Compressor 02', 'Plant A', 'Running');
CALL add_asset ('Compressor 03', 'Plant A', 'Down');
CALL add_asset ('Compressor 04', 'Plant A', 'Running');
CALL add_asset ('Compressor 05', 'Plant A', 'Running');
CALL add_asset ('Compressor 06', 'Plant A', 'Running');
CALL add_asset ('Compressor 07', 'Plant A', 'Running');
CALL add_asset ('Compressor 08', 'Plant A', 'Running');
CALL add_asset ('Compressor 09', 'Plant A', 'Running');
CALL add_asset ('Compressor 10', 'Plant A', 'Running');
CALL add_asset ('Robot Arm 01', 'Plant B', 'Maintenance');
CALL add_asset ('Robot Arm 02', 'Plant B', 'Running');
CALL add_asset ('Robot Arm 03', 'Plant A', 'Down');
CALL add_asset ('Robot Arm 04', 'Plant B', 'Running');
CALL add_asset ('Robot Arm 05', 'Plant A', 'Idle');
CALL add_asset ('Robot Arm 06', 'Plant C', 'Running');
CALL add_asset ('Robot Arm 07', 'Plant D', 'Idle');
CALL add_asset ('Robot Arm 08', 'Plant E', 'Running');
CALL add_asset ('Robot Arm 09', 'Plant A', 'Maintenance');
CALL add_asset ('Ion 10', 'Plant F', 'Maintenance');
CALL add_asset ('Ion 01', 'Plant Z', 'Maintenance');
CALL add_asset ('Ion 02', 'Plant X', 'Running');
CALL add_asset ('Ion 03', 'Plant C', 'Running');
CALL add_asset ('Ion 04', 'Plant V', 'Maintenance');
CALL add_asset ('Ion 05', 'Plant A', 'Down');
CALL add_asset ('Ion 06', 'Plant A', 'Running');
CALL add_asset ('Ion 07', 'Plant A', 'Running');
CALL add_asset ('Ion 08', 'Plant A', 'Idle');
CALL add_asset ('Ion 09', 'Plant A', 'Idle');
CALL add_asset ('Ion 10', 'Plant A', 'Down');