apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-update
  namespace: assetops
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase
          image: "{{ .Values.liquibase.image.repository }}:{{ .Values.liquibase.image.tag }}"
          imagePullPolicy: {{ .Values.liquibase.image.pullPolicy }}
          command:
            - /liquibase/docker-entrypoint.sh
          args:
            - --defaultsFile=/liquibase/infra/liquibase/liquibase.yaml
            - update
