databaseChangeLog:
  - changeSet:
      id: 001-create-assets-table
      author: sudheesh
      changes:
        - sqlFile:
            path: ../tables/assets.sql
            relativeToChangelogFile: true
      rollback:
        - sql: "DROP TABLE IF EXISTS assets;"
