databaseChangeLog:
  - changeSet:
      id: 003-create-notify-function
      author: sudheesh
      runOnChange: true
      changes:
        - sqlFile:
            path: ../procedures/notify_app_config_change.sql
            relativeToChangelogFile: true
            splitStatements: false
      rollback:
        - sql: "DROP FUNCTION IF EXISTS notify_app_config_change() CASCADE;"
