databaseChangeLog:
  - changeSet:
      id: 004-create-notify-trigger
      author: sudheesh
      changes:
        - sqlFile:
            path: ../triggers/trg_app_config_change.sql
            relativeToChangelogFile: true
      rollback:
        - sql: "DROP TRIGGER IF EXISTS trg_app_config_change ON app_config;"
