databaseChangeLog:
  - changeSet:
      id: 005-create-add-asset-procedure
      author: sudheesh
      changes:
        - sqlFile:
            path: ../procedures/add_asset.sql
            relativeToChangelogFile: true
            splitStatements: false
      rollback:
        - sql: "DROP PROCEDURE IF EXISTS add_asset(VARCHAR, VARCHAR, VARCHAR);"
