databaseChangeLog:
  - changeSet:
      id: 006_create_audit_log_table
      author: sudheesh
      changes:
        - createTable:
            tableName: audit_logs
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: table_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: action
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: changed_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: payload
                  type: JSONB
