databaseChangeLog:
  - changeSet:
      id: 007-add-seed-assets
      author: sudheesh
      context: test
      changes:
        - sqlFile:
            path: ../procedures/add_seed_assets.sql
            relativeToChangelogFile: true
            splitStatements: false
      rollback:
        - sql: "TRUNCATE TABLE assets RESTART IDENTITY;"