databaseChangeLog:
  - changeSet:
      id: 008-add-seed-app-config
      author: sudheesh
      runOnChange: true
      context: test
      changes:
        - sqlFile:
            path: ../procedures/add_app_config_procedure.sql
            relativeToChangelogFile: true
            splitStatements: false
        - sqlFile:
            path: ../procedures/add_seed_config.sql
            relativeToChangelogFile: true
      rollback:
        - sql: "TRUNCATE TABLE app_config;"
        - sql: "DROP PROCEDURE IF EXISTS add_app_config(TEXT, TEXT);"